name: ${project.name}
version: ${project.version}
main: eu.kennytv.aacbungeemessages.spigot.AACBungeeMessagesSpigot
author: KennyTV

commands:
  aacnotify:
    description: Sends an AAC notify message to other Bukkit/Spigot servers with this plugin.